### ISSUE TITLE
Add Superforth Basics page

### ISSUE THREAD

**Issue by Xanderplayz17** [TheRealMichaelWang/superforth#24]
Use this page for teaching the reader how to use variables, make a hello world program, and the other basics of superforth.

**Comment by Xanderplayz17** [comment]
bruh

**Comment by Xanderplayz17** [comment]
I closed this because I realized doing stuff 1 step at a time.

**Comment by TheRealMichaelWang** [comment]
I dont quite understand what you mean, but if you'd like a few good examples to superforth, [check out the examples folder](https://github.com/TheRealMichaelWang/superforth/tree/main/examples).
