### ISSUE TITLE
Add Text & Printing Text page on the wiki.

### ISSUE THREAD

**Issue by Xanderplayz17** [TheRealMichaelWang/superforth#25]
Pretty much it explains text and explains how to print text.

**Comment by TheRealMichaelWang** [comment]
Yeah I haven't exactly set the standard library in stone as of yet, but I'll add a quick summary for you here:

All you gotta do is `import "io.txt";` (which you can get from [here](https://github.com/TheRealMichaelWang/superforth/blob/main/examples/io.txt)) and call one of several functions
| Identifier | What it does | Arguments | Returns | Example Usage |
|---|---|---|---|---|
|`print`|Writes to stdout, without a newline at the end|`array<char>`|`nothing`|`print("Hello There");`|
|`println`|Same as prints but writes a newline at the end|`array<char>`|`nothing`|`println("Ends with a new line");`|
|`put_char`|Writes a single character to stdout|`char`|`nothing`|`put_char('m');`|
|`input`|Grabs a line of input(max 4096 chars)|N/A|`array<char>`|`auto str = input();`|

Also, to convert ints/floats to strings, and vice versa please refer to the following functions found in [`string.txt`](https://github.com/TheRealMichaelWang/superforth/blob/main/examples/string.txt).
| Identifier | What it does | Arguments | Returns | Example Usage |
| --- | --- | --- | --- | --- |
|`itos`|Converts an int to string|`int`|`array<char>`|`array<char> numstr = itos(69);`|
|`ftos`|Converts a float to string|`float`|`array<char>`|`auto str = ftos(4.2);`|
|`stoi`|Converts a string to int|`array<char>`|`int`|`int i = stoi(input());`|
|`stof`|Converts a string to float|`array<char>`|`float`|`float f = stof(input());`|
Those aren't the only supported functionalities in `string.txt`, but these are the few that are most relevant to i/o.

Anyways, it's probably best to download everything in the [`stdlib` folder](https://github.com/TheRealMichaelWang/superforth/tree/main/stdlib) and put it in your SuperForth executables working directory.

**Comment by Xanderplayz16** [comment]
Ok.
