### ISSUE TITLE
Gives a unexpected token error but gives no location of the error.

### ISSUE THREAD

**Issue by Xanderplayz16** [TheRealMichaelWang/superforth#34]
I made a hello world program and after changing import to include, it gave me a invalid token error but no location of the error. Here is my code:
`include "io.txt";`
`print("Hello, World!")`

**Comment by TheRealMichaelWang** [comment]
You need to add a semicolon after each statement.
```
include "io.txt";
print("Hello, World!")
```
If its a syntax error, the compiler would give you the row and column number in addition to everything left on the said errors line.

**Comment by Xanderplayz16** [comment]
Oh.
